<script type="text/javascript">
  FusionCharts.ready(function(){
	//var str="[{"label":"Sudhir Ranjan","value":"3"},{"label":"Francis Meher","value":"6"}]";
	//var myArray = <?php echo json_encode($hospital_doc_to_encode); ?>;
   var heightChart = new FusionCharts({
      type: 'msline',
      renderAt: 'chart-container',
      width: '750',
      height: '600',
      dataFormat: 'json',
      dataSource: {
        "chart": {
          "caption": "",
          "subcaption": "Baby <?php echo $patient_tab[0]['patient_name'];?> Head Circumference",
		  "xAxisName": "Month",
          "yAxisName": "cm",
		  "yAxisMinValue": "28",
		  "yAxisMaxvalue": "51",
		   "linethickness": "0.75",
		  "anchoralpha": "0",
         "showBorder": "0",
        "showShadow": "0",
		"drawCrossLine": "0.75", 
		"crossLineColor": "#0d0d0d",
        "showCanvasBorder": "0",
        "usePlotGradientColor": "0",
        "legendBorderAlpha": "0",
        "legendShadow": "0",
        "showAxisLines": "0",
        "showAlternateHGridColor": "0",
        "divlineThickness": "1",
        "divLineIsDashed": "1",
        "divLineDashLen": "1",
        "divLineGapLen": "1",
        "vDivLineColor": "#99ccff",
          "vDivLineThickness": "1",
          "vDivLineAlpha": "70",
          "vDivLineDashed": "1",
          "vDivLineDashLen": "3",
          "vDivLineDashGap": "2",
        "showValues": "0",
          "theme": "fint",
		  "connectNullData": "1"
        },
        "categories": [{
          "category": [{
            "label": "0"
          }, {
            "label": "1"
          }, {
            "label": "2"
          }, {
            "label": "3"
          }, {
            "label": "4"
          }, {
            "label": "5"
          }, {
            "label": "6"
          }, {
            "label": "7"
          }, {
            "label": "8"
          }, {
            "label": "9"
          }, {
            "label": "10"
          }, {
            "label": "11"
          }, {
            "label": "12"
          }, {
            "label": "13"
          }, {
            "label": "14"
          }, {
            "label": "15"
          }, {
            "label": "16"
          }, {
            "label": "17"
          }, {
            "label": "18"
          }, {
            "label": "19"
          }, {
            "label": "20"
          }, {
            "label": "21"
          }, {
            "label": "22"
          }, {
            "label": "23"
          }, {
            "label": "24"
          }]
        }],
        "dataset": [{
		  "seriesname": "3rd",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "32.1"
          }, {
            "value": "35.1"
          }, {
            "value": "36.9"
          }, {
            "value": "38.3"
          }, {
            "value": "39.4"
          }, {
            "value": "40.3"
          }, {
            "value": "41.0"
          }, {
            "value": "41.7"
          }, {
            "value": "42.2"
          }, {
            "value": "42.6"
          }, {
            "value": "43.0"
          }, {
            "value": "43.4"
          }, {
            "value": "43.6"
          }, {
            "value": "43.9"
          }, {
            "value": "44.1"
          }, {
            "value": "44.3"
          }, {
            "value": "44.5"
          }, {
            "value": "44.7"
          }, {
            "value": "44.9"
          }, {
            "value": "45.0"
          }, {
            "value": "45.2"
          }, {
            "value": "45.3"
          }, {
            "value": "45.4"
          }, {
            "value": "45.6"
          }, {
            "value": "45.7"
          }<?php } else { ?>
		  {
            "value": "31.7"
          }, {
            "value": "34.3"
          }, {
            "value": "36.0"
          }, {
            "value": "37.2"
          }, {
            "value": "38.2"
          }, {
            "value": "39.0"
          }, {
            "value": "39.7"
          }, {
            "value": "40.4"
          }, {
            "value": "40.9"
          }, {
            "value": "41.3"
          }, {
            "value": "41.7"
          }, {
            "value": "42.0"
          }, {
            "value": "42.3"
          }, {
            "value": "42.6"
          }, {
            "value": "42.9"
          }, {
            "value": "43.1"
          }, {
            "value": "43.3"
          }, {
            "value": "43.5"
          }, {
            "value": "43.6"
          }, {
            "value": "43.8"
          }, {
            "value": "44.0"
          }, {
            "value": "44.1"
          }, {
            "value": "44.3"
          }, {
            "value": "44.4"
          }, {
            "value": "44.6"
          }<?php } ?>],
        },{
			
          "seriesname": "Actual Head Circumference",
          "data": [<?php 
		  for($i=0;$i<=24;$i++){
			  $j=0;
		  foreach($getChatValue1 as $listVal){ 
		  $current_date   = new DateTime($listVal['growth_date']);
		  $expected_date     = new DateTime($patient_tab[0]['DOB']);
			$corrected_diff = $expected_date->diff($current_date);
			
		  if($corrected_diff->m == $i){ ?>{
            "value": "<?php echo $listVal['head_circum']; ?>"
          },<?php $j++;
		  break;} 
		 
		  }
		  if($j==0){
			 ?>{
            "value": ""
          },<?php 
		  }
		  }?>],
        }, {
		  "seriesname": "15th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "33.1"
          }, {
            "value": "36.1"
          }, {
            "value": "37.9"
          }, {
            "value": "39.3"
          }, {
            "value": "40.4"
          }, {
            "value": "41.3"
          }, {
            "value": "42.1"
          }, {
            "value": "42.7"
          }, {
            "value": "43.2"
          }, {
            "value": "43.7"
          }, {
            "value": "44.1"
          }, {
            "value": "44.4"
          }, {
            "value": "44.7"
          }, {
            "value": "45.0"
          }, {
            "value": "45.2"
          }, {
            "value": "45.5"
          }, {
            "value": "45.6"
          }, {
            "value": "45.8"
          }, {
            "value": "46.0"
          }, {
            "value": "46.2"
          }, {
            "value": "46.3"
          }, {
            "value": "46.4"
          }, {
            "value": "46.6"
          }, {
            "value": "46.7"
          }, {
            "value": "46.8"
          }<?php } else { ?>
		  {
            "value": "32.7"
          }, {
            "value": "35.3"
          }, {
            "value": "37.0"
          }, {
            "value": "38.2"
          }, {
            "value": "39.3"
          }, {
            "value": "40.1"
          }, {
            "value": "40.8"
          }, {
            "value": "41.5"
          }, {
            "value": "42.0"
          }, {
            "value": "42.4"
          }, {
            "value": "42.8"
          }, {
            "value": "43.2"
          }, {
            "value": "43.5"
          }, {
            "value": "43.8"
          }, {
            "value": "44.0"
          }, {
            "value": "44.2"
          }, {
            "value": "44.4"
          }, {
            "value": "44.6"
          }, {
            "value": "44.8"
          }, {
            "value": "45.0"
          }, {
            "value": "45.1"
          }, {
            "value": "45.3"
          }, {
            "value": "45.4"
          }, {
            "value": "45.6"
          }, {
            "value": "45.7"
          }<?php } ?>],
        },{
		 "seriesname": "Median",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "34.5"
          }, {
            "value": "37.3"
          }, {
            "value": "39.1"
          }, {
            "value": "40.5"
          }, {
            "value": "41.6"
          }, {
            "value": "42.6"
          }, {
            "value": "43.3"
          }, {
            "value": "44.0"
          }, {
            "value": "44.5"
          }, {
            "value": "45.0"
          }, {
            "value": "45.4"
          }, {
            "value": "45.8"
          }, {
            "value": "46.1"
          }, {
            "value": "46.3"
          }, {
            "value": "46.6"
          }, {
            "value": "46.8"
          }, {
            "value": "47.0"
          }, {
            "value": "47.2"
          }, {
            "value": "47.4"
          }, {
            "value": "47.5"
          }, {
            "value": "47.7"
          }, {
            "value": "47.8"
          }, {
            "value": "48.0"
          }, {
            "value": "48.1"
          }, {
            "value": "48.3"
          }<?php } else { ?>
		  {
            "value": "33.9"
          }, {
            "value": "36.5"
          }, {
            "value": "38.3"
          }, {
            "value": "39.5"
          }, {
            "value": "40.6"
          }, {
            "value": "41.5"
          }, {
            "value": "42.2"
          }, {
            "value": "42.8"
          }, {
            "value": "43.4"
          }, {
            "value": "43.8"
          }, {
            "value": "44.2"
          }, {
            "value": "44.6"
          }, {
            "value": "44.9"
          }, {
            "value": "45.2"
          }, {
            "value": "45.4"
          }, {
            "value": "45.7"
          }, {
            "value": "45.9"
          }, {
            "value": "46.1"
          }, {
            "value": "46.2"
          }, {
            "value": "46.4"
          }, {
            "value": "46.6"
          }, {
            "value": "46.7"
          }, {
            "value": "46.9"
          }, {
            "value": "47.0"
          }, {
            "value": "47.2"
          }<?php } ?>],
        },{
		 "seriesname": "85th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "35.8"
          }, {
            "value": "38.5"
          }, {
            "value": "40.3"
          }, {
            "value": "41.7"
          }, {
            "value": "42.9"
          }, {
            "value": "43.8"
          }, {
            "value": "44.6"
          }, {
            "value": "45.3"
          }, {
            "value": "45.8"
          }, {
            "value": "46.3"
          }, {
            "value": "46.7"
          }, {
            "value": "47.1"
          }, {
            "value": "47.4"
          }, {
            "value": "47.7"
          }, {
            "value": "47.9"
          }, {
            "value": "48.2"
          }, {
            "value": "48.4"
          }, {
            "value": "48.6"
          }, {
            "value": "48.7"
          }, {
            "value": "48.9"
          }, {
            "value": "49.1"
          }, {
            "value": "49.2"
          }, {
            "value": "49.4"
          }, {
            "value": "49.5"
          }, {
            "value": "49.7"
          }<?php } else { ?>
		  {
            "value": "35.1"
          }, {
            "value": "37.8"
          }, {
            "value": "39.5"
          }, {
            "value": "40.8"
          }, {
            "value": "41.9"
          }, {
            "value": "42.8"
          }, {
            "value": "43.5"
          }, {
            "value": "44.2"
          }, {
            "value": "44.7"
          }, {
            "value": "45.2"
          }, {
            "value": "45.6"
          }, {
            "value": "46.0"
          }, {
            "value": "46.3"
          }, {
            "value": "46.6"
          }, {
            "value": "46.8"
          }, {
            "value": "47.1"
          }, {
            "value": "47.3"
          }, {
            "value": "47.5"
          }, {
            "value": "47.7"
          }, {
            "value": "47.8"
          }, {
            "value": "48.0"
          }, {
            "value": "48.2"
          }, {
            "value": "48.3"
          }, {
            "value": "48.5"
          }, {
            "value": "48.6"
          }<?php } ?>],
        },{
		 "seriesname": "97th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "36.9"
          }, {
            "value": "39.5"
          }, {
            "value": "41.3"
          }, {
            "value": "42.7"
          }, {
            "value": "43.9"
          }, {
            "value": "44.8"
          }, {
            "value": "45.6"
          }, {
            "value": "46.3"
          }, {
            "value": "46.9"
          }, {
            "value": "47.4"
          }, {
            "value": "47.8"
          }, {
            "value": "48.2"
          }, {
            "value": "48.5"
          }, {
            "value": "48.8"
          }, {
            "value": "49.0"
          }, {
            "value": "49.3"
          }, {
            "value": "49.5"
          }, {
            "value": "49.7"
          }, {
            "value": "49.9"
          }, {
            "value": "50.0"
          }, {
            "value": "50.2"
          }, {
            "value": "50.4"
          }, {
            "value": "50.5"
          }, {
            "value": "50.7"
          }, {
            "value": "50.8"
          }<?php } else { ?>
		  {
            "value": "36.1"
          }, {
            "value": "38.8"
          }, {
            "value": "40.5"
          }, {
            "value": "41.9"
          }, {
            "value": "43.0"
          }, {
            "value": "43.9"
          }, {
            "value": "44.6"
          }, {
            "value": "45.3"
          }, {
            "value": "45.9"
          }, {
            "value": "46.3"
          }, {
            "value": "46.8"
          }, {
            "value": "47.1"
          }, {
            "value": "47.5"
          }, {
            "value": "47.7"
          }, {
            "value": "48.0"
          }, {
            "value": "48.2"
          }, {
            "value": "48.5"
          }, {
            "value": "48.7"
          }, {
            "value": "48.8"
          }, {
            "value": "49.0"
          }, {
            "value": "49.2"
          }, {
            "value": "49.4"
          }, {
            "value": "49.5"
          }, {
            "value": "49.7"
          }, {
            "value": "49.8"
          }<?php } ?>],
        }]
      }
    });
	
	var weightChart = new FusionCharts({
      type: 'msline',
      renderAt: 'chart-container1',
      width: '750',
      height: '600',
      dataFormat: 'json',
      dataSource: {
        "chart": {
          "caption": "",
          "subcaption": "Baby <?php echo $patient_tab[0]['patient_name'];?> Weight Chart",
		  "xAxisName": "Month",
          "yAxisName": "kgs",
		  "yAxisMinValue": "0",
		  "yAxisMaxvalue": "15",
           "linethickness": "0.75",
		  "anchoralpha": "0",
         "showBorder": "0",
        "showShadow": "0",
		"drawCrossLine": "0.75", 
		"crossLineColor": "#0d0d0d",
        "showCanvasBorder": "0",
        "usePlotGradientColor": "0",
        "legendBorderAlpha": "0",
        "legendShadow": "0",
        "showAxisLines": "0",
        "showAlternateHGridColor": "0",
        "divlineThickness": "1",
        "divLineIsDashed": "1",
        "divLineDashLen": "1",
        "divLineGapLen": "1",
        "vDivLineColor": "#99ccff",
          "vDivLineThickness": "1",
          "vDivLineAlpha": "70",
          "vDivLineDashed": "1",
          "vDivLineDashLen": "3",
          "vDivLineDashGap": "2",
        "showValues": "0",
          "theme": "fint",
		  "connectNullData": "1"
        },
        "categories": [{
          "category": [{
            "label": "0"
          }, {
            "label": "1"
          }, {
            "label": "2"
          }, {
            "label": "3"
          }, {
            "label": "4"
          }, {
            "label": "5"
          }, {
            "label": "6"
          }, {
            "label": "7"
          }, {
            "label": "8"
          }, {
            "label": "9"
          }, {
            "label": "10"
          }, {
            "label": "11"
          }, {
            "label": "12"
          }, {
            "label": "13"
          }, {
            "label": "14"
          }, {
            "label": "15"
          }, {
            "label": "16"
          }, {
            "label": "17"
          }, {
            "label": "18"
          }, {
            "label": "19"
          }, {
            "label": "20"
          }, {
            "label": "21"
          }, {
            "label": "22"
          }, {
            "label": "23"
          }, {
            "label": "24"
          }]
        }],
        "dataset": [{
          "seriesname": "3rd",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "2.5"
          }, {
            "value": "3.4"
          }, {
            "value": "4.4"
          }, {
            "value": "5.1"
          }, {
            "value": "5.6"
          }, {
            "value": "6.1"
          }, {
            "value": "6.4"
          }, {
            "value": "6.7"
          }, {
            "value": "7.0"
          }, {
            "value": "7.2"
          }, {
            "value": "7.5"
          }, {
            "value": "7.7"
          }, {
            "value": "7.8"
          }, {
            "value": "8.0"
          }, {
            "value": "8.2"
          }, {
            "value": "8.4"
          }, {
            "value": "8.5"
          }, {
            "value": "8.7"
          }, {
            "value": "8.9"
          }, {
            "value": "9.0"
          }, {
            "value": "9.2"
          }, {
            "value": "9.3"
          }, {
            "value": "9.5"
          }, {
            "value": "9.7"
          }, {
            "value": "9.8"
          }<?php } else { ?>
		  {
            "value": "2.4"
          }, {
            "value": "3.2"
          }, {
            "value": "4.0"
          }, {
            "value": "4.6"
          }, {
            "value": "5.1"
          }, {
            "value": "5.5"
          }, {
            "value": "5.8"
          }, {
            "value": "6.1"
          }, {
            "value": "6.3"
          }, {
            "value": "6.6"
          }, {
            "value": "6.8"
          }, {
            "value": "7.0"
          }, {
            "value": "7.1"
          }, {
            "value": "7.3"
          }, {
            "value": "7.5"
          }, {
            "value": "7.7"
          }, {
            "value": "7.8"
          }, {
            "value": "8.0"
          }, {
            "value": "8.2"
          }, {
            "value": "8.3"
          }, {
            "value": "8.5"
          }, {
            "value": "8.7"
          }, {
            "value": "8.8"
          }, {
            "value": "9.0"
          }, {
            "value": "9.2"
          }<?php } ?>],
        },{
          "seriesname": "Actual Weight",
          "data": [<?php for($i=0;$i<=24;$i++){
			  $j=0;
		  foreach($getChatValue1 as $listVal){ 
		  $current_date   = new DateTime($listVal['growth_date']);
		  $expected_date     = new DateTime($patient_tab[0]['DOB']);
			$corrected_diff = $expected_date->diff($current_date);
			
		  if($corrected_diff->m == $i){ ?>{
            "value": "<?php echo $actual_weight=$listVal['weight']/1000; ?>"
          },<?php $j++;
		  break;} 
		 
		 // $i++;
		  }
		  if($j==0){
			 ?>{
            "value": ""
          },<?php 
		  }
		  } ?>],
        }, {
          "seriesname": "15th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "2.9"
          }, {
            "value": "3.9"
          }, {
            "value": "4.9"
          }, {
            "value": "5.6"
          }, {
            "value": "6.2"
          }, {
            "value": "6.7"
          }, {
            "value": "7.1"
          }, {
            "value": "7.4"
          }, {
            "value": "7.7"
          }, {
            "value": "7.9"
          }, {
            "value": "8.2"
          }, {
            "value": "8.4"
          }, {
            "value": "8.6"
          }, {
            "value": "8.8"
          }, {
            "value": "9.0"
          }, {
            "value": "9.2"
          }, {
            "value": "9.4"
          }, {
            "value": "9.6"
          }, {
            "value": "9.7"
          }, {
            "value": "9.9"
          }, {
            "value": "10.1"
          }, {
            "value": "10.3"
          }, {
            "value": "10.5"
          }, {
            "value": "10.6"
          }, {
            "value": "10.8"
          }<?php } else { ?>
		  {
            "value": "2.8"
          }, {
            "value": "3.6"
          }, {
            "value": "4.5"
          }, {
            "value": "5.1"
          }, {
            "value": "5.6"
          }, {
            "value": "6.1"
          }, {
            "value": "6.4"
          }, {
            "value": "6.7"
          }, {
            "value": "7.0"
          }, {
            "value": "7.3"
          }, {
            "value": "7.5"
          }, {
            "value": "7.7"
          }, {
            "value": "7.9"
          }, {
            "value": "8.1"
          }, {
            "value": "8.3"
          }, {
            "value": "8.5"
          }, {
            "value": "8.7"
          }, {
            "value": "8.8"
          }, {
            "value": "9.0"
          }, {
            "value": "9.2"
          }, {
            "value": "9.4"
          }, {
            "value": "9.6"
          }, {
            "value": "9.8"
          }, {
            "value": "9.9"
          }, {
            "value": "10.1"
          }<?php } ?>],
        },{
          "seriesname": "Median",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "3.3"
          }, {
            "value": "4.5"
          }, {
            "value": "5.6"
          }, {
            "value": "6.4"
          }, {
            "value": "7.0"
          }, {
            "value": "7.5"
          }, {
            "value": "7.9"
          }, {
            "value": "8.3"
          }, {
            "value": "8.6"
          }, {
            "value": "8.9"
          }, {
            "value": "9.2"
          }, {
            "value": "9.4"
          }, {
            "value": "9.6"
          }, {
            "value": "9.9"
          }, {
            "value": "10.1"
          }, {
            "value": "10.3"
          }, {
            "value": "10.5"
          }, {
            "value": "10.7"
          }, {
            "value": "10.9"
          }, {
            "value": "11.1"
          }, {
            "value": "11.3"
          }, {
            "value": "11.5"
          }, {
            "value": "11.8"
          }, {
            "value": "12.0"
          }, {
            "value": "12.2"
          }<?php } else { ?>
		  {
            "value": "3.2"
          }, {
            "value": "4.2"
          }, {
            "value": "5.1"
          }, {
            "value": "5.8"
          }, {
            "value": "6.4"
          }, {
            "value": "6.9"
          }, {
            "value": "7.3"
          }, {
            "value": "7.6"
          }, {
            "value": "7.9"
          }, {
            "value": "8.2"
          }, {
            "value": "8.5"
          }, {
            "value": "8.7"
          }, {
            "value": "8.9"
          }, {
            "value": "9.2"
          }, {
            "value": "9.4"
          }, {
            "value": "9.6"
          }, {
            "value": "9.8"
          }, {
            "value": "10.0"
          }, {
            "value": "10.2"
          }, {
            "value": "10.4"
          }, {
            "value": "10.6"
          }, {
            "value": "10.9"
          }, {
            "value": "11.1"
          }, {
            "value": "11.3"
          }, {
            "value": "11.5"
          } <?php } ?>],
        },{
          "seriesname": "85th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "3.9"
          }, {
            "value": "5.1"
          }, {
            "value": "6.3"
          }, {
            "value": "7.2"
          }, {
            "value": "7.9"
          }, {
            "value": "8.4"
          }, {
            "value": "8.9"
          }, {
            "value": "9.3"
          }, {
            "value": "9.6"
          }, {
            "value": "10.0"
          }, {
            "value": "10.3"
          }, {
            "value": "10.5"
          }, {
            "value": "10.8"
          }, {
            "value": "11.1"
          }, {
            "value": "11.3"
          }, {
            "value": "11.6"
          }, {
            "value": "11.8"
          }, {
            "value": "12.0"
          }, {
            "value": "12.3"
          }, {
            "value": "12.5"
          }, {
            "value": "12.7"
          }, {
            "value": "13.0"
          }, {
            "value": "13.2"
          }, {
            "value": "13.4"
          }, {
            "value": "13.7"
          }<?php } else { ?>
		  {
            "value": "3.7"
          }, {
            "value": "4.8"
          }, {
            "value": "5.9"
          }, {
            "value": "6.7"
          }, {
            "value": "7.3"
          }, {
            "value": "7.8"
          }, {
            "value": "8.3"
          }, {
            "value": "8.7"
          }, {
            "value": "9.0"
          }, {
            "value": "9.3"
          }, {
            "value": "9.6"
          }, {
            "value": "9.9"
          }, {
            "value": "10.2"
          }, {
            "value": "10.4"
          }, {
            "value": "10.7"
          }, {
            "value": "10.9"
          }, {
            "value": "11.2"
          }, {
            "value": "11.4"
          }, {
            "value": "11.6"
          }, {
            "value": "11.9"
          }, {
            "value": "12.1"
          }, {
            "value": "12.4"
          }, {
            "value": "12.6"
          }, {
            "value": "12.8"
          }, {
            "value": "13.1"
          }<?php } ?>],
        },{
          "seriesname": "97th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "4.3"
          }, {
            "value": "5.7"
          }, {
            "value": "7.0"
          }, {
            "value": "7.9"
          }, {
            "value": "8.6"
          }, {
            "value": "9.2"
          }, {
            "value": "9.7"
          }, {
            "value": "10.2"
          }, {
            "value": "10.5"
          }, {
            "value": "10.9"
          }, {
            "value": "11.2"
          }, {
            "value": "11.5"
          }, {
            "value": "11.8"
          }, {
            "value": "12.1"
          }, {
            "value": "12.4"
          }, {
            "value": "12.7"
          }, {
            "value": "12.9"
          }, {
            "value": "13.2"
          }, {
            "value": "13.5"
          }, {
            "value": "13.7"
          }, {
            "value": "14.0"
          }, {
            "value": "14.3"
          }, {
            "value": "14.5"
          }, {
            "value": "14.8"
          }, {
            "value": "15.1"
          }<?php } else { ?>
		  {
            "value": "4.2"
          }, {
            "value": "5.4"
          }, {
            "value": "6.5"
          }, {
            "value": "7.4"
          }, {
            "value": "8.1"
          }, {
            "value": "8.7"
          }, {
            "value": "9.2"
          }, {
            "value": "9.6"
          }, {
            "value": "10.0"
          }, {
            "value": "10.4"
          }, {
            "value": "10.7"
          }, {
            "value": "11.0"
          }, {
            "value": "11.3"
          }, {
            "value": "11.6"
          }, {
            "value": "11.9"
          }, {
            "value": "12.2"
          }, {
            "value": "12.5"
          }, {
            "value": "12.7"
          }, {
            "value": "13.0"
          }, {
            "value": "13.3"
          }, {
            "value": "13.5"
          }, {
            "value": "13.8"
          }, {
            "value": "14.1"
          }, {
            "value": "14.3"
          }, {
            "value": "14.6"
          }<?php } ?>],
        }]
      }
    });
	var circumChart = new FusionCharts({
      type: 'msline',
      renderAt: 'chart-container2',
      width: '750',
      height: '600',
      dataFormat: 'json',
      dataSource: {
        "chart": {
          "caption": "",
          "subcaption": "Baby <?php echo $patient_tab[0]['patient_name'];?>  Length Chart",
		  "xAxisName": "Month",
          "yAxisName": "cm",
		  "yAxisMinValue": "32",
		  "yAxisMaxvalue": "95",
		  "xAxisMaxvalue": "25",
          "linethickness": "0.75",
		  "anchoralpha": "0",
         "showBorder": "0",
        "showShadow": "0",
		"drawCrossLine": "0.75", 
		"crossLineColor": "#0d0d0d",
        "showCanvasBorder": "0",
        "usePlotGradientColor": "0",
        "legendBorderAlpha": "0",
        "legendShadow": "0",
        "showAxisLines": "0",
        "showAlternateHGridColor": "0",
        "divlineThickness": "1",
        "divLineIsDashed": "1",
        "divLineDashLen": "1",
        "divLineGapLen": "1",
        "vDivLineColor": "#99ccff",
          "vDivLineThickness": "1",
          "vDivLineAlpha": "70",
          "vDivLineDashed": "1",
          "vDivLineDashLen": "3",
          "vDivLineDashGap": "2",
        "showValues": "0",
          "theme": "fint",
		  "connectNullData": "1"
        },
        "categories": [{
          "category": [{
            "label": "0"
          }, {
            "label": "1"
          }, {
            "label": "2"
          }, {
            "label": "3"
          }, {
            "label": "4"
          }, {
            "label": "5"
          }, {
            "label": "6"
          }, {
            "label": "7"
          }, {
            "label": "8"
          }, {
            "label": "9"
          }, {
            "label": "10"
          }, {
            "label": "11"
          }, {
            "label": "12"
          }, {
            "label": "13"
          }, {
            "label": "14"
          }, {
            "label": "15"
          }, {
            "label": "16"
          }, {
            "label": "17"
          }, {
            "label": "18"
          }, {
            "label": "19"
          }, {
            "label": "20"
          }, {
            "label": "21"
          }, {
            "label": "22"
          }, {
            "label": "23"
          }, {
            "label": "24"
          }]
        }],
        "dataset": [{
          "seriesname": "3rd",
          "data": [{
            "value": "46.3"
          }, {
            "value": "51.1"
          }, {
            "value": "54.7"
          }, {
            "value": "57.6"
          }, {
            "value": "60.0"
          }, {
            "value": "61.9"
          }, {
            "value": "63.6"
          }, {
            "value": "65.1"
          }, {
            "value": "66.5"
          }, {
            "value": "67.7"
          }, {
            "value": "69.0"
          }, {
            "value": "70.2"
          }, {
            "value": "71.3"
          }, {
            "value": "72.4"
          }, {
            "value": "73.4"
          }, {
            "value": "74.4"
          }, {
            "value": "75.4"
          }, {
            "value": "76.3"
          }, {
            "value": "77.2"
          }, {
            "value": "78.1"
          }, {
            "value": "78.9"
          }, {
            "value": "79.7"
          }, {
            "value": "80.5"
          }, {
            "value": "81.3"
          }, {
            "value": "82.1"
          }],
        },{
          "seriesname": "Actual Length",
          "data": [ <?php for($i=0;$i<=24;$i++){
			  $j=0;
		  foreach($getChatValue1 as $listVal){ 
		  $current_date   = new DateTime($listVal['growth_date']);
		  $expected_date     = new DateTime($patient_tab[0]['DOB']);
			$corrected_diff = $expected_date->diff($current_date);
			
		  if($corrected_diff->m == $i){ ?>{
            "value": "<?php echo $listVal['height']; ?>"
          },<?php $j++;
		  break;} 
		 
		 // $i++;
		  }
		  if($j==0){
			 ?>{
            "value": ""
          },<?php 
		  }
		  } ?>],
        },{
          "seriesname": "15th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "47.9"
          }, {
            "value": "52.7"
          }, {
            "value": "56.4"
          }, {
            "value": "59.3"
          }, {
            "value": "61.7"
          }, {
            "value": "63.7"
          }, {
            "value": "65.4"
          }, {
            "value": "66.9"
          }, {
            "value": "68.3"
          }, {
            "value": "69.6"
          }, {
            "value": "70.9"
          }, {
            "value": "72.1"
          }, {
            "value": "73.3"
          }, {
            "value": "74.4"
          }, {
            "value": "75.5"
          }, {
            "value": "76.5"
          }, {
            "value": "77.5"
          }, {
            "value": "78.5"
          }, {
            "value": "79.5"
          }, {
            "value": "80.4"
          }, {
            "value": "81.3"
          }, {
            "value": "82.2"
          }, {
            "value": "83.0"
          }, {
            "value": "83.8"
          }, {
            "value": "84.6"
          }<?php } else { ?>
		  {
            "value": "47.2"
          }, {
            "value": "51.7"
          }, {
            "value": "55.0"
          }, {
            "value": "57.6"
          }, {
            "value": "59.8"
          }, {
            "value": "61.7"
          }, {
            "value": "63.4"
          }, {
            "value": "64.9"
          }, {
            "value": "66.3"
          }, {
            "value": "67.6"
          }, {
            "value": "68.9"
          }, {
            "value": "70.2"
          }, {
            "value": "71.3"
          }, {
            "value": "72.5"
          }, {
            "value": "73.6"
          }, {
            "value": "74.7"
          }, {
            "value": "75.7"
          }, {
            "value": "76.7"
          }, {
            "value": "77.7"
          }, {
            "value": "78.7"
          }, {
            "value": "79.6"
          }, {
            "value": "80.5"
          }, {
            "value": "81.4"
          }, {
            "value": "82.2"
          }, {
            "value": "83.1"
          }<?php } ?>],
        }, {
          "seriesname": "Median",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "49.9"
          }, {
            "value": "54.7"
          }, {
            "value": "58.4"
          }, {
            "value": "61.4"
          }, {
            "value": "63.9"
          }, {
            "value": "65.9"
          }, {
            "value": "67.6"
          }, {
            "value": "69.2"
          }, {
            "value": "70.6"
          }, {
            "value": "72.0"
          }, {
            "value": "73.3"
          }, {
            "value": "74.5"
          }, {
            "value": "75.7"
          }, {
            "value": "76.9"
          }, {
            "value": "78.0"
          }, {
            "value": "79.1"
          }, {
            "value": "80.2"
          }, {
            "value": "81.2"
          }, {
            "value": "82.3"
          }, {
            "value": "83.2"
          }, {
            "value": "84.2"
          }, {
            "value": "85.1"
          }, {
            "value": "86.0"
          }, {
            "value": "86.9"
          }, {
            "value": "87.8"
          }<?php } else { ?>
		  {
            "value": "49.1"
          }, {
            "value": "53.7"
          }, {
            "value": "57.1"
          }, {
            "value": "59.8"
          }, {
            "value": "62.1"
          }, {
            "value": "64.0"
          }, {
            "value": "65.7"
          }, {
            "value": "67.3"
          }, {
            "value": "68.7"
          }, {
            "value": "70.1"
          }, {
            "value": "71.5"
          }, {
            "value": "72.8"
          }, {
            "value": "74.0"
          }, {
            "value": "75.2"
          }, {
            "value": "76.4"
          }, {
            "value": "77.5"
          }, {
            "value": "78.6"
          }, {
            "value": "79.7"
          }, {
            "value": "80.7"
          }, {
            "value": "81.7"
          }, {
            "value": "82.7"
          }, {
            "value": "83.7"
          }, {
            "value": "84.6"
          }, {
            "value": "85.5"
          }, {
            "value": "86.4"
          }<?php } ?>],
        },{
          "seriesname": "85th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "51.8"
          }, {
            "value": "56.7"
          }, {
            "value": "60.5"
          }, {
            "value": "63.5"
          }, {
            "value": "66.0"
          }, {
            "value": "68.1"
          }, {
            "value": "69.8"
          }, {
            "value": "71.4"
          }, {
            "value": "72.9"
          }, {
            "value": "74.3"
          }, {
            "value": "75.6"
          }, {
            "value": "77.0"
          }, {
            "value": "78.2"
          }, {
            "value": "79.4"
          }, {
            "value": "80.6"
          }, {
            "value": "81.8"
          }, {
            "value": "82.9"
          }, {
            "value": "84.0"
          }, {
            "value": "85.1"
          }, {
            "value": "86.1"
          }, {
            "value": "87.1"
          }, {
            "value": "88.1"
          }, {
            "value": "89.1"
          }, {
            "value": "90.0"
          }, {
            "value": "91.0"
          }<?php } else { ?>
		  {
            "value": "51.1"
          }, {
            "value": "55.7"
          }, {
            "value": "59.2"
          }, {
            "value": "62.0"
          }, {
            "value": "64.3"
          }, {
            "value": "66.3"
          }, {
            "value": "68.1"
          }, {
            "value": "69.7"
          }, {
            "value": "71.2"
          }, {
            "value": "72.6"
          }, {
            "value": "74.0"
          }, {
            "value": "75.4"
          }, {
            "value": "76.7"
          }, {
            "value": "77.9"
          }, {
            "value": "79.2"
          }, {
            "value": "80.3"
          }, {
            "value": "81.5"
          }, {
            "value": "82.6"
          }, {
            "value": "83.7"
          }, {
            "value": "84.8"
          }, {
            "value": "85.8"
          }, {
            "value": "86.8"
          }, {
            "value": "87.8"
          }, {
            "value": "88.8"
          }, {
            "value": "89.8"
          }<?php } ?>],
        },{
          "seriesname": "97th",
          "data": [<?php if($patient_tab[0]['patient_gen']==1){ ?>
		  {
            "value": "53.4"
          }, {
            "value": "58.4"
          }, {
            "value": "62.2"
          }, {
            "value": "65.3"
          }, {
            "value": "67.8"
          }, {
            "value": "69.9"
          }, {
            "value": "71.6"
          }, {
            "value": "73.2"
          }, {
            "value": "74.7"
          }, {
            "value": "76.2"
          }, {
            "value": "77.6"
          }, {
            "value": "78.9"
          }, {
            "value": "80.2"
          }, {
            "value": "81.5"
          }, {
            "value": "82.7"
          }, {
            "value": "83.9"
          }, {
            "value": "85.1"
          }, {
            "value": "86.2"
          }, {
            "value": "87.3"
          }, {
            "value": "88.4"
          }, {
            "value": "89.5"
          }, {
            "value": "90.5"
          }, {
            "value": "91.6"
          }, {
            "value": "92.6"
          }, {
            "value": "93.6"
          }<?php } else { ?>
		  {
            "value": "52.7"
          }, {
            "value": "57.4"
          }, {
            "value": "60.9"
          }, {
            "value": "63.8"
          }, {
            "value": "66.2"
          }, {
            "value": "68.2"
          }, {
            "value": "70.0"
          }, {
            "value": "71.6"
          }, {
            "value": "73.2"
          }, {
            "value": "74.7"
          }, {
            "value": "76.1"
          }, {
            "value": "77.5"
          }, {
            "value": "78.9"
          }, {
            "value": "80.2"
          }, {
            "value": "81.4"
          }, {
            "value": "82.7"
          }, {
            "value": "83.9"
          }, {
            "value": "85.0"
          }, {
            "value": "86.2"
          }, {
            "value": "87.3"
          }, {
            "value": "88.4"
          }, {
            "value": "89.4"
          }, {
            "value": "90.5"
          }, {
            "value": "91.5"
          }, {
            "value": "92.5"
          }<?php } ?>],
        }]
      }
    });
	
    heightChart.render();
	weightChart.render();
	circumChart.render();
});

</script>

								